# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Grpc.kd_pb2 as kd__pb2


class Collaborative_LearningStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateIdx = channel.unary_unary(
                '/Collaborative_Learning/UpdateIdx',
                request_serializer=kd__pb2.IdxRequest.SerializeToString,
                response_deserializer=kd__pb2.IdxResponse.FromString,
                )
        self.UpdateGrad = channel.unary_unary(
                '/Collaborative_Learning/UpdateGrad',
                request_serializer=kd__pb2.GradRequest.SerializeToString,
                response_deserializer=kd__pb2.GradResponse.FromString,
                )


class Collaborative_LearningServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateIdx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGrad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Collaborative_LearningServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateIdx': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIdx,
                    request_deserializer=kd__pb2.IdxRequest.FromString,
                    response_serializer=kd__pb2.IdxResponse.SerializeToString,
            ),
            'UpdateGrad': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGrad,
                    request_deserializer=kd__pb2.GradRequest.FromString,
                    response_serializer=kd__pb2.GradResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Collaborative_Learning', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Collaborative_Learning(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateIdx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Collaborative_Learning/UpdateIdx',
            kd__pb2.IdxRequest.SerializeToString,
            kd__pb2.IdxResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGrad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Collaborative_Learning/UpdateGrad',
            kd__pb2.GradRequest.SerializeToString,
            kd__pb2.GradResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
